export enum LearningSessionsActionTypes {
  LoadLearningSession = 'Load learning session',
  LoadLearningSessionSuccess = 'Load learning session success',
  LoadAllLearningSessionsSuccess = 'Loads the overview',
  LoadAllLearningSessions = 'Loading the overview success',
  LoadEditSession = 'Load edit',
  LoadEditSuccess = 'load edit success',
  SaveLearningSession = 'Save edit',
  SaveLearningSessionSuccess = 'Save edit success',
  DeleteAllLearningSessions = 'Delete all',
  DeleteAllLearningSessionsSuccess = 'Delete all success',
  Delete = 'Delete',
  DeleteLearningSessionSuccess = 'Delete success',
  LoadRunFacts = 'Load run facts',
  LoadRunFactsSuccess = 'Load run facts success',
  SelectNextRunFact = 'Select next run fact',
  SelectPreviousRunFact = 'Select previous run fact',
  SelectSession = 'Select session',
  ReshuffleRunFacts = 'Reshuffle run facts',
  SelectNextSessionRunFacts = 'Select next session run facts',
  SelectNextSessionRunFactsSuccess = 'Select next session run facts success'
}
